version: 2 

sources:
  - name: raw_db
    database: semantic_layer
    schema: raw_db
    tables:
      - name: hr_raw_
        columns:
          - name: employeeid
            tests:
              - not_null
              - unique

models: 
  - name: dim_employee
    description: "Dimension table for employee data"

  - name: dim_job
    description: "Includes details about the position"

  - name: dim_performance
    description: "Staging table for sentiment data"

  - name: dim_salary
    description: "Includes all information related with employees salary"

  - name: fct_employees
    description: "Table including all data needed to evaluate the working profile of the employee."

  - name: min_max_scaler
    config:
      materialized: table
      tags: ['python']
      packages:
        - pandas
        - scikit-learn