version: 2 

sources:
  - name: semantic
    database: semantic_layer
    schema: raw_db
    tables:
      - name: hr_raw_
        columns:
          - name: employeeid
            tests:
              - not_null
              - unique
